### ISSUE TITLE
打开微信内置浏览器的F12后，如何hook自己的脚本？

### ISSUE THREAD

**Issue by iptag** [JaveleyQAQ/WeChatOpenDevTools-Python#101]
调试只能在内置微信浏览器打开的某网页，发现有无限debugger的js代码，网上找了一些办法，好像都没办法绕过，应该需要在网页加载前hook掉debugger代码才可以，请教下大佬，hook代码应该放置在哪里？初步看，应该放在\scripts\WechatWin.dll\hook.js内，但放入其中的代码好像并没有执行

**Comment by JaveleyQAQ** [comment]
阉割版控制台，功能不全。 试试fd把js代码重写一下，或者第一个请求之前断点在控制台hook

**Comment by iptag** [comment]
> 阉割版控制台，功能不全。 试试fd把js代码重写一下，或者第一个请求之前断点在控制台hook

了解，感谢！

**Comment by luckycat0426** [comment]
> 阉割版控制台，功能不全。 试试fd把js代码重写一下，或者第一个请求之前断点在控制台hook

请问fd是fiddler吗，微信浏览器我抓包出来好像没看到请求，数据流走的wxtls加密传输，是不是特定版本的微信是走http请求加载js的。
