### ISSUE TITLE
找到9185版本的hook地址，但是有问题。无法完全开启devtools，看不到源代码功能。

### ISSUE THREAD

**Issue by sparkholder** [JaveleyQAQ/WeChatOpenDevTools-Python#103]
{
  "LaunchAppletBegin": "0x26F2A83",
  "MenuItemDevToolsString":"0x2609028",
  "jscode":"0x26B154D",
  "SwitchVersion":"0x24BF4F4",
  "Version":9185
}
![image](https://github.com/user-attachments/assets/4c3c4ee6-5b68-490c-aacf-73b68ef82c81)

**Comment by sparkholder** [comment]
包括11065版本，同样的问题：
{
  "LaunchAppletBegin": "0x2888883",
  "MenuItemDevToolsString":"0x278AF58",
  "jscode":"0x26B154D",
  "SwitchVersion":"0x24BF4F4",
  "Version":11065
}
![image](https://github.com/user-attachments/assets/72fb9765-766a-4671-a963-a09bd1f49e58)

**Comment by JaveleyQAQ** [comment]
位置没找对，把第四段地址周围信息贴出来

**Comment by sparkholder** [comment]
![image](https://github.com/user-attachments/assets/09cc4ea1-1efc-46e9-bcff-c6b36df4b2d4)
![image](https://github.com/user-attachments/assets/b345441e-a269-4b3e-a71b-b3d64a655532)
第四个地址应该是在这里面吧。

**Comment by sparkholder** [comment]
ok，hook到了
{
  "LaunchAppletBegin": "0x2888883",
  "MenuItemDevToolsString":"0x278AF58",
  "jscode":"0x26B154D",
  "SwitchVersion":"0x26B9CD8",
  "Version":11065
}
![image](https://github.com/user-attachments/assets/2ee14978-a97f-4a86-b393-2f327ce88787)
