### ISSUE TITLE
# Mac系统可以打开devtools,但是里面没有抓包界面以及源码

### ISSUE THREAD

**Issue by gts3337500** [JaveleyQAQ/WeChatOpenDevTools-Python#104]
![image](https://github.com/user-attachments/assets/441c7163-d7ee-42e7-a9d8-fe4ccff6bce7)
![image](https://github.com/user-attachments/assets/bb1f13aa-3186-4d7e-9660-412977e7b539)
小白一枚,请问这个是有配置直接打开就好,还是咱们这个强制打开的问题?

**Comment by JaveleyQAQ** [comment]
更新了，试试不知道是不是忘记加版本逻辑的问题

**Comment by gts3337500** [comment]
最新版可以使用,感谢大佬

**Comment by gts3337500** [comment]
但是全局搜索不能使用进度条一直卡在这里
![image](https://github.com/user-attachments/assets/f49c0090-c442-40d2-9b91-c075186ed286)
