### ISSUE TITLE
提供9193版本小程序的地址

### ISSUE THREAD

**Issue by rouyi-tmc** [JaveleyQAQ/WeChatOpenDevTools-Python#107]
{
	"LaunchAppletBegin": "0x26F1B5C",
	"MenuItemDevToolsString": "0x2700D14",
	"SwitchVersion": "0x2554A54",
	"Version": 9193
}

**Comment by rouyi-tmc** [comment]
不是一个bug

**Comment by shangdev** [comment]
@rouyi-tmc 请问这个怎么找偏移呢，看csdn上教程是附加调试WeChatAppEx.exe进程，但是有好多个WeChatAppEx.exe进程，试了几个搜索字符串都找不到LaunchApplet关键字
