### ISSUE TITLE
mac m芯片开虚拟机的arm版Windows是不是不能用这个脚本

### ISSUE THREAD

**Issue by god0me** [JaveleyQAQ/WeChatOpenDevTools-Python#108]
<img width="1155" alt="image" src="https://github.com/user-attachments/assets/38e844cb-552d-48dc-a386-f4efffe86089">

**Comment by JaveleyQAQ** [comment]
是的 arm都不支持 隔壁有arm版本的

**Comment by harwinvoid** [comment]
隔壁的链接可以发下吗
