### ISSUE TITLE
# 问题标题：简洁且具有描述性的问题标题

### ISSUE THREAD

**Issue by huangxxxtian** [JaveleyQAQ/WeChatOpenDevTools-Python#109]
| 100分  | 我在运行最新的的时候遇到了一个问题，在翻阅文档和视频后，这里是报错截图，

![1a5cd8889e9651c389cf6be8805ce4b](https://github.com/user-attachments/assets/0251116c-5e54-42ff-b36e-63d9f9c5aa72)

## 问题描述
- 请在这里提供问题的详细描述，包括您遇到的具体问题和任何相关的背景信息。
mac的电脑。m的芯片，一运行是就这个错，是不支持m芯片的mac嘛
Error injecting into WeChat PID 5250: [Errno 2] No such file or directory: '/Users/xxx/Library/Containers/com.tencent.xinWeChat/Data/Library/Application Support/com.tencent.xinWeChat/2.0b4.0.9/d9b250afda5d21e9383b632b912f9e83/Message/MessageTemp/a9d99fbc0ec7e41ff42b2decb80667f5/File/WeChatOpenDevTools-Python-main/utils/../configs/../configs/address_13080710_x64.json'

**Comment by JaveleyQAQ** [comment]
不支持arm
