### ISSUE TITLE
WeChatWin3.9.8.25_x64.zip下载不了

### ISSUE THREAD

**Issue by Padavan2019** [JaveleyQAQ/WeChatOpenDevTools-Python#11]
https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/releases/download/0.1/WeChatWin3.9.8.25_x64.zip
提示找不到

**Comment by JaveleyQAQ** [comment]
这方法被检测了 不推荐用

**Comment by yesan** [comment]
> 这方法被检测了 不推荐用

那现在内置浏览器现在也不能打开F12了吗

**Comment by Bigyayaya** [comment]
> 这方法被检测了 不推荐用

是不是小程序的f12还能正常用 内置浏览器f12嘎了

**Comment by JaveleyQAQ** [comment]
> > 这方法被检测了 不推荐用
> 
> 是不是小程序的f12还能正常用 内置浏览器f12嘎了

没噶 就是这个方法容易被检测了 还没写别的

**Comment by JaveleyQAQ** [comment]
更新内置浏览器问题了 @Padavan2019 @Bigyayaya @yesan
