### ISSUE TITLE
# 问题标题：unable to access process with pid 93890 from the current user account

### ISSUE THREAD

**Issue by LWJ0718** [JaveleyQAQ/WeChatOpenDevTools-Python#110]
使用最新版本微信3.8.8，mac系统，运行主程序提示
Error injecting into WeChat PID 93890: unable to access process with pid 93890 from the current user account
Injected into WeChat instance PID: 93890, Version: 13080812

**Comment by JaveleyQAQ** [comment]
https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/issues/49
