### ISSUE TITLE
启动后提示注入成功，但是最终显示Error injecting into WeChat PID 9824: the connection is closed

### ISSUE THREAD

**Issue by mingzitainanle** [JaveleyQAQ/WeChatOpenDevTools-Python#111]
## 问题描述
通过IDA工具，找到了三个偏移参数，然后按照要求增加了address文件，也改了hook.js，执行命令提示启动提示连接失败
![image](https://github.com/user-attachments/assets/f72453f6-c823-4114-b005-b539e9c27697)

## 环境信息

1. PC：Win11
2. 微信客户端：3.9.11.25
3. 内置浏览器版本：11205
4. Python版本：3.12.0
5. frida版本：16.4.8（16.1.x也试过了报错一样）

address版本
> {
>     "LaunchAppletBegin": "0x28A07A8",
>     "MenuItemDevToolsString":"0x28AD361",
>     "SwitchVersion":"0x26D1CE8",
>     "Version":11205
> }

## 复现步骤
1. 通过py追代码看到应该是在.\WeChatOpenDevTools-Python-main\utils\commons.py inject_wechatEx(){script.load()}这段报错，但是没有具体明细原因。

**Comment by JaveleyQAQ** [comment]
第三个地址找错导致堆栈崩溃了

**Comment by MarkTina** [comment]
> SwitchVersion

兄弟，最后的 address 地址是多少 11205 版本的

**Comment by MarkTina** [comment]
最后注入成功 11205 版本；
配置如下：
{
  "LaunchAppletBegin": "0x28A070C",
  "MenuItemDevToolsString": "0x28AE121",
  "SwitchVersion": "0x26D1CE8",
  "Version": 11205
}

**Comment by MarkTina** [comment]
OK. your email has been received.
