### ISSUE TITLE
colorama  没有初始化的问题

### ISSUE THREAD

**Issue by sang8052** [JaveleyQAQ/WeChatOpenDevTools-Python#12]
项目中 colorama  组件没有初始化，导致编译后的程序运行时字体颜色异常 
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31176926/07f81232-17c0-4415-87e8-dfdfba97a440)

**Comment by pruidong** [comment]
用cmd运行python main.py没出现这个问题，你可以下载源码运行试一下。

**Comment by JaveleyQAQ** [comment]
忽略-。- win10 cmd貌似就是不支持彩色输出
