### ISSUE TITLE
# mac m1 运行报错：No such file or directory

### ISSUE THREAD

**Issue by shixiaoxianga** [JaveleyQAQ/WeChatOpenDevTools-Python#121]
运行 python main.py -x 报以下错误

Error injecting into WeChat PID 82544: [Errno 2] No such file or directory: '/Users/xxx/development/my-project/py-code/WeChatOpenDevTools-Python/utils/../configs/../configs/address_13080813_x64.json'

Version. 3.8.8 (28538)

python3.12

**Comment by shixiaoxianga** [comment]
(base) xxx@AXiangMacBook-Pro WeChatOpenDevTools-Python % ps aux | grep 'WeChatAppEx' |  grep -v 'grep' | grep  "wmpf-mojo-handle" 
xxx    82544   0.0  0.1 444915312  18272   ??  S    11:02AM   0:01.61 /Applications/微信 2.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx --log-level=2 --lang=zh-CN --wechat-files-path=/Urs/xiangzhongwei/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet --no-codecache --product-id=1000 --wechat-sub-user-agent=MicroMessenger/6.8.0(0x16080000) MacWechat/3.8.8(0x13080813) --appshim-flags=7 --client_version=319293459 --bundle-id=5A4RE8SF68.com.tencent.xinWeChat --wmpf-mojo-handle=1074878660

**Comment by RoryXiang** [comment]
> (base) xxx@AXiangMacBook-Pro WeChatOpenDevTools-Python % ps aux | grep 'WeChatAppEx' | grep -v 'grep' | grep "wmpf-mojo-handle" xxx 82544 0.0 0.1 444915312 18272 ?? S 11:02AM 0:01.61 /Applications/微信 2.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx --log-level=2 --lang=zh-CN --wechat-files-path=/Urs/xiangzhongwei/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet --no-codecache --product-id=1000 --wechat-sub-user-agent=MicroMessenger/6.8.0(0x16080000) MacWechat/3.8.8(0x13080813) --appshim-flags=7 --client_version=319293459 --bundle-id=5A4RE8SF68.com.tencent.xinWeChat --wmpf-mojo-handle=1074878660

兄弟，你这个是怎么创建新版本的address配置文件的。
