### ISSUE TITLE
# Error injecting into WeChat PID 28960: unexpectedly failed with error code: 0x00000057 Injected into WeChat instance PID: 28960, Version: 8555

### ISSUE THREAD

**Issue by 1769782410** [JaveleyQAQ/WeChatOpenDevTools-Python#124]
## 问题描述
-打开小程序后显示Session Session(pid=87888) detached, removing from active sessions. ，然后直接退出了，微信还在，但是小程序直接闪退

## 环境信息
- **操作系统及版本**：win10
- **编程语言和版本**：python38

## 复现步骤
1. 步骤一：当前小程序版本: 8555
2. 步骤二：微信版本:3.9.10.19
3.步骤三 :  源码运行python main.py -x

## 实际结果
直接显示错误信息
**

Error injecting into WeChat PID 28960: unexpectedly failed with error code: 0x00000057
Injected into WeChat instance PID: 28960, Version: 8555
**

---

请在提交问题之前，检查您的描述是否清晰、准确，并且提供了足够的信息以便他人理解您的问题。感谢您的合作！

**Comment by 1769782410** [comment]
使用3.9以上版本 重新按照依赖包

**Comment by chenwei-zhao** [comment]
> 使用3.9以上版本 重新按照依赖包

有用，解决了我的问题
