### ISSUE TITLE
# 感觉是不是有使用时长的限制？我早上用了几个小时，没有任何问题，中午吃饭回来就用不了了

### ISSUE THREAD

**Issue by oryjk** [JaveleyQAQ/WeChatOpenDevTools-Python#129]
## 问题描述
- 我早上用了几个小时，没有任何问题，中午吃饭回来就用不了了

## 环境信息
- **操作系统及版本**：windows11
- **编程语言和版本**：例如 Python 3.12.0
- **GitHub 仓库名称和问题相关的代码分支**：主分支

![image](https://github.com/user-attachments/assets/ce9c9a28-48fd-4547-b6e8-e45c7a000f68)

**Comment by gwenhe** [comment]
我也遇到此问题，后来排查发现是微信自动更新了小程序版本。卸载重新安装微信即可

**Comment by CutelyRose** [comment]
怎末屏蔽更新

**Comment by JaveleyQAQ** [comment]
常见问题 c点可以解决大部分问题
