### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by xinshous** [JaveleyQAQ/WeChatOpenDevTools-Python#13]
大佬为什么未找到呢？是因为小程序版本问题吗？
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/99654681/ec9628ac-6cbc-4531-a9ec-c54e4ddc3336)
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/99654681/30cf1647-58e5-4310-ba28-c7bbd02efe81)

**Comment by JaveleyQAQ** [comment]
第一次遇到这个版本的...在configs文件里没这个版本内存地址，你打包一下这个9069发我

**Comment by prettykernel** [comment]
我也刷出了 9069 和 9053。解决方案是：
退出微信，把两个文件夹删除，重新登录，随便打开一个小程序，就会变为 8555 文件夹。
应该是微信对部分用户开启的灰度测试

**Comment by xinshous** [comment]
> 第一次遇到这个版本的...在configs文件里没这个版本内存地址，你打包一下这个9069发我

我删掉微信重新下载了一下，现在解决了

**Comment by keatonLiu** [comment]
9069 和 9053的地址可不可以兼容一下？
