### ISSUE TITLE
请问 你是怎么打包成exe的呢？

### ISSUE THREAD

**Issue by a410202049** [JaveleyQAQ/WeChatOpenDevTools-Python#15]
pyinstaller  -F main.py  我这样打包 执行 exe 会报错 
   ModuleNotFoundError: No module named 'utils'

**Comment by JaveleyQAQ** [comment]
nuitka --include-data-dir=configs=configs  --include-data-dir=scripts=scripts  --remove-output --onefile --standalone main.py
