### ISSUE TITLE
注入浏览器会卡死

### ISSUE THREAD

**Issue by q6415369** [JaveleyQAQ/WeChatOpenDevTools-Python#18]
注入微信浏览器就卡死，重启微信后注入小程序也会提示[-] 未找到匹配版本的微信进程或微信未运行（没有注入浏览器之前是正常的）
微信版本：3.9.9.43
[+] 命令行参数："D:\Program Files (x86)\Tencent\WeChat\[3.9.9.43]\mmcrashpad_handler64.exe" --no-rate-limit --database=C:\Users\tang\AppData\Roaming\Tencent\WeChat\cr
ash --annotation=crash_notify=1 "--annotation=ext_info={\"app_call_name\":\"微信\",\"app_name\":\"WechatWindows\",\"app_path\":\"D:\\Program Files (x86)\\Tencent\\WeC
hat\\WeChat.exe\",\"dwbuild\":\"43\",\"log_path\":\"C:\\Users\\tang\\AppData\\Roaming\\Tencent\\WeChat\\crash\",\"major_ver\":\"3\",\"minor_ver\":\"0\",\"module_name\
":\"Wechat_Windows\",\"modules_dir\":\"D:\\Program Files (x86)\\Tencent\\WeChat\\[3.9.9.43]\",\"product\":\"WECHAT\",\"report_type\":\"9999\",\"restart_app_cmd\":\"\"
,\"upload_choice\":\"3\",\"version\":\"1661536555\"}" --annotation=log_path=C:\Users\tang\AppData\Roaming\Tencent\WeChat\crash --annotation=product=WECHAT --initial-client-data=0x5a0,0x5a4,0x5a8,0x5ac,0x59c,0x5b0,0x7ffae43be3f8,0x7ffae43be438,0x7ffae43be468
[+] 命令行参数："C:\Users\tang\AppData\Roaming\Tencent\WeChat\XPlugin\Plugins\RadiumWMPF\8555\extracted\runtime\WeChatAppEx.exe" --log-level=0 --xweb-enable-inspect=1
 --helper-handle-value=619419332 --wechat-files-path="C:\Users\tang\Documents\WeChat Files\\" --product-id=1000 --wechat-sub-user-agent="MicroMessenger/7.0.20.1781(0x
6700143B) WindowsWechat(0x6309092b)" --wmpf_extra_config="{ \"reportId\":-1, \"version\":8555, \"cmd6@default\":\"true\", \"cmd8@default\":\"true\" }" --web-translate --client_version=1661536555 --wmpf-mojo-handle=4112 --helper-handle-value=619419332 --wechat-files-path="C:\Users\tang\Documents\WeChat Files\\" --product-id=1000 --wechat-sub-user-agent="MicroMessenger/7.0.20.1781(0x
6700143B) WindowsWechat(0x6309092b)" --wmpf_extra_config="{ \"reportId\":-1, \"version\":8555, \"cmd6@default\":\"true\", \"cmd8@default\":\"true\" }" --web-translate --client_version=1661536555 --wmpf-mojo-handle=4112

**Comment by JaveleyQAQ** [comment]
这个问题在常见问题一栏有说明
