### ISSUE TITLE
微信内置浏览器注入容易闪退

### ISSUE THREAD

**Issue by q6415369** [JaveleyQAQ/WeChatOpenDevTools-Python#19]
微信版本:3.9.9.43
运行命令：python  main.py -c
问题：
输入指令后，微信启动到登录界面过会，微信就会闪退了,控制台界面是没有报错的

**Comment by JaveleyQAQ** [comment]
看一下之前类似问题， 我目前用win10 没遇到过，截止现在我还是正常使用
