### ISSUE TITLE
大佬你好，能否添加一个F12快捷键

### ISSUE THREAD

**Issue by jem1997** [JaveleyQAQ/WeChatOpenDevTools-Python#2]
有些小程序限制pc端打开，无法调出devtools。可以设置个快捷键直接调出devtools

**Comment by JaveleyQAQ** [comment]
暂时加不了，切换devtools中文后无法看到数据也没办法解决

**Comment by jem1997** [comment]
感觉回复，已知悉。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月24日(星期三) 中午1:14
收件人: ***@***.***&gt;; 
抄送: "By. 将来时丶 ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [JaveleyQAQ/WeChatOpenDevTools-Python] 大佬你好，能否添加一个F12快捷键 (Issue #2)





 
暂时加不了，切换devtools中文后无法看到数据也没办法解决

**Comment by a410202049** [comment]
如果 开启浏览器的 调试啊？公众号网页的

**Comment by JaveleyQAQ** [comment]
> 

看README

**Comment by a410202049** [comment]
@JaveleyQAQ 直接替换dll的方式 容易被监测。我之前被提示过。。。

**Comment by a410202049** [comment]
@JaveleyQAQ 请问下大佬 开启浏览器的dev的思路是什么啊？怕到时候微信版本更新用不了。

**Comment by JaveleyQAQ** [comment]
> @JaveleyQAQ 请问下大佬 开启浏览器的dev的思路是什么啊？怕到时候微信版本更新用不了。

改一下逻辑，你diff一下修改的跟原始dll的差别就明白了
