### ISSUE TITLE
9079 devtool没有network栏

### ISSUE THREAD

**Issue by keatonLiu** [JaveleyQAQ/WeChatOpenDevTools-Python#20]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/57738324/ea38e420-fb4d-4ec5-b4f7-ab74b465db58)

**Comment by GG-o1** [comment]
+1

**Comment by leon0503** [comment]
+1

**Comment by JaveleyQAQ** [comment]
解决了
