### ISSUE TITLE
3.9.43版本已经不能使用

### ISSUE THREAD

**Issue by eanproeanpro** [JaveleyQAQ/WeChatOpenDevTools-Python#24]
![图片](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/129724732/91a4e988-789e-42fc-93ea-970a4e676297)
运行提示检测不到版本，直接闪退

**Comment by theside9** [comment]
不要用release，试试直接python main.py，实测可以

**Comment by JaveleyQAQ** [comment]
> 不要用release，试试直接python main.py，实测可以

release 我没往里面打包9079 所以找不到

**Comment by rvluxx** [comment]
> > 不要用发布，试试直接Python main.py，实测可以
> 
> release 我没往里面打包9079 所以找不到

3.9.9.43 9079 通过源代码执行可以正常注入 hook到小程序加载，但是无法还原F12

**Comment by JaveleyQAQ** [comment]
> > > 不要用发布，试试直接Python main.py，实测可以
> > 
> > 
> > release 我没往里面打包9079 所以找不到
> 
> 3.9.9.43 9079 通过源代码执行可以正常注入 hook到小程序加载，但是无法还原F12

是昨天更新的没办法还原吗？

**Comment by rvluxx** [comment]
> > > > 不要用发布，试试直接Python main.py，实测可以
> > > 
> > > 
> > > release 我没往里面打包9079 所以找不到
> > 
> > 
> > 3.9.9.43 9079 通过源代码执行可以正常注入 hook到小程序加载，但是无法还原F12
> 
> 是昨天更新的没办法还原吗？

刚才重新拉取库又试了下依然不行，怀疑是WechatAppHtml基址出了问题，WechatWebHtml可以正常hook到

**Comment by rvluxx** [comment]
> > > > 不要用发布，试试直接Python main.py，实测可以
> > > 
> > > 
> > > release 我没往里面打包9079 所以找不到
> > 
> > 
> > 3.9.9.43 9079 通过源代码执行可以正常注入 hook到小程序加载，但是无法还原F12
> 
> 是昨天更新的没办法还原吗？

重新拉取后可以使用了 感谢
