### ISSUE TITLE
3.9.9.43 devtools 没了

### ISSUE THREAD

**Issue by lishunt** [JaveleyQAQ/WeChatOpenDevTools-Python#26]
<img width="278" alt="image" src="https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/30864550/1ad00eb4-d6a0-4d28-89f3-308ed1b2d5d4">
<img width="324" alt="image" src="https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/30864550/31fbad8c-562b-4851-bbab-c77ee8bf8e84">

**Comment by JaveleyQAQ** [comment]
小程序版本 运行的说exe还是cmd说一下

**Comment by lishunt** [comment]
> 小程序版本 运行的说exe还是cmd说一下

cmd,python main.py -x

**Comment by zanx213** [comment]
我cmd不行 小程序9079

**Comment by JaveleyQAQ** [comment]
> 我cmd不行 小程序9079

是最新版的吗 前两天刚更新
