### ISSUE TITLE
# 问题标题：简洁且具有描述性的问题标题

### ISSUE THREAD

**Issue by 3H3H3H3** [JaveleyQAQ/WeChatOpenDevTools-Python#29]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/68240913/a39f55dc-8e7f-44e9-8b34-cb31b92eaca2)
搜索就卡住了，怎么解决，师傅

**Comment by JaveleyQAQ** [comment]
我也没办法解决全局搜索问题，单页面ctrl+f吧
