### ISSUE TITLE
用这个会被微信封号吗？？？

### ISSUE THREAD

**Issue by haiderackermann** [JaveleyQAQ/WeChatOpenDevTools-Python#3]
如题，我要不要弄个小号来测试

**Comment by JaveleyQAQ** [comment]
我只能说干啥都有风险，wx插件红包改主题这些理论上也是改数据会被封的

**Comment by wdxwj** [comment]
@JaveleyQAQ  有一个在命令行增加xweb那个你试过吗？我试了没反应

**Comment by JaveleyQAQ** [comment]
> @JaveleyQAQ 有一个在命令行增加xweb那个你试过吗？我试了没反应

你说内置浏览器hook命令行还是启动程序方式添加命令？

**Comment by wdxwj** [comment]
> > @JaveleyQAQ 有一个在命令行增加xweb那个你试过吗？我试了没反应
> 
> 你说内置浏览器hook命令行还是启动程序方式添加命令？

hook命令行，我成功了，不过只是开启浏览器的，小程序的说不定也行我觉得

**Comment by JaveleyQAQ** [comment]
> > > @JaveleyQAQ 有一个在命令行增加xweb那个你试过吗？我试了没反应
> > 
> > 
> > 你说内置浏览器hook命令行还是启动程序方式添加命令？
> 
> hook命令行，我成功了，不过只是开启浏览器的，小程序的说不定也行我觉得

项目里就是hook小程序的，不过hook浏览器的没加上去

**Comment by wdxwj** [comment]
> > > > @JaveleyQAQ 有一个在命令行增加xweb那个你试过吗？我试了没反应
> > > 
> > > 
> > > 你说内置浏览器hook命令行还是启动程序方式添加命令？
> > 
> > 
> > hook命令行，我成功了，不过只是开启浏览器的，小程序的说不定也行我觉得
> 
> 项目里就是hook小程序的，不过hook浏览器的没加上去

frida hook 是不是比改内存的inline hook安全
