### ISSUE TITLE
frida拉不起 程序

### ISSUE THREAD

**Issue by LeToNode** [JaveleyQAQ/WeChatOpenDevTools-Python#30]
## 问题描述
-  从执行顺序来看，应该是要frida拉起程序，然后执行注入，但是最新的代码来看，始终是无法拉起程序进行注入。
-  从说明文档看，说是要先启动程序，所以是不是有什么矛盾的地方。

## 环境信息
- **操作系统及版本**：windows 11
- **编程语言和版本**：python3.12
- **相关库或框架及版本**：例如 Django 3.1.7
- **GitHub 仓库名称和问题相关的代码分支**：如果有的话，提供仓库链接和分支信息。
- 
<img width="845" alt="2f2afb8bf97261fc80b7caf6dcad0449" src="https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/909138/3c75713e-d872-4378-a259-93b077d1e4c0">

---

请在提交问题之前，检查您的描述是否清晰、准确，并且提供了足够的信息以便他人理解您的问题。感谢您的合作！

**Comment by LeToNode** [comment]
不排除是arm芯片的关系，

**Comment by JaveleyQAQ** [comment]
看着是firda注入进程报错，进程可能被其他软件占用了或者进程id错误，可以尝试在注入进程前print看看注入进程否正确，先从-x开始调试， 最好是找个干净的虚拟机只装微信再尝试

**Comment by LeToNode** [comment]
找另外的电脑试了下，是ok的，我回头再找一个电脑看下。
现在devtools是正常展示了，但是network里面只有图片请求之类的信息，其它的网络请求并未出现，不知道自带浏览器是否使用了其它协议的方式绕过devtools的network的网络请求显示。
