### ISSUE TITLE
9079版本可能还有检测没过完？

### ISSUE THREAD

**Issue by daisixuan** [JaveleyQAQ/WeChatOpenDevTools-Python#32]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/42495803/395a30a0-e18f-4eb5-a9a5-9157548d3d4d)
打开小程序显示hook加载成功了 但是直接卡主然后闪退了

**Comment by JiaLeDe** [comment]
我的也显示这样

**Comment by JaveleyQAQ** [comment]
已知问题
