### ISSUE TITLE
9097小程序没有F12devtools

### ISSUE THREAD

**Issue by USnwst** [JaveleyQAQ/WeChatOpenDevTools-Python#33]
变成了这个样式
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/95516635/fd14b9ad-cd05-450d-9145-c01014da4ffe)

![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/95516635/e3fc1dc0-02b5-40b0-922b-de8c0debebb7)

**Comment by JaveleyQAQ** [comment]
试一下这个分支下的https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/tree/dev

**Comment by flying0228** [comment]
打开闪退
