### ISSUE TITLE
devtools问题

### ISSUE THREAD

**Issue by Wlbak** [JaveleyQAQ/WeChatOpenDevTools-Python#35]
开启devtools后，

1、使用中文，抓不到包

2、使用搜索功能，一直卡住，无法搜索

**Comment by JaveleyQAQ** [comment]
[# 问题标题：search搜索会卡死，一直都搜不出东西 · Issue #39 · JaveleyQAQ/WeChatOpenDevTools-Python](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/issues/39)
