### ISSUE TITLE
# 问题标题：search搜索会卡死，一直都搜不出东西

### ISSUE THREAD

**Issue by orgcomcn** [JaveleyQAQ/WeChatOpenDevTools-Python#39]
## 问题描述
- search搜索不出东西，一直都搜不出东西，我使用2个月之前的版本，search正常可以搜索，我git pull以后，search无法搜索出东西， 不知道什么原因，大佬请赐教。

## 环境信息
- **操作系统及版本** ：Windows 10
- **编程语言和版本**： Python 3.11.0b4
- **当前小程序版本**： 8555 
![WechatIMG32](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/49893317/fa8c5991-74ed-4672-a94e-3dee890e555f)

**Comment by JaveleyQAQ** [comment]
微信版本问题，自从8555开始就加限制了，能力有限，没办法保存缓存。

**Comment by JaveleyQAQ** [comment]
> 那这个有办法降低微信的版本吗？不让他是8555.

看说明文档，有个历史版本下载

**Comment by 1136623363** [comment]
同8555无法搜索。切了好多次也换不了版本

**Comment by pian-f** [comment]
> -。- 8555没尝试，我在9105上搜索是没有问题的 ![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/132129852/68aecb2b-e6f5-45da-afe0-02b5719c842a)

您使用的微信版本是哪个?

**Comment by fre1ak** [comment]
9105使用的哪个微信版本呢?
