### ISSUE TITLE
3.9.10.19 9115 提示成功, 但没有出现 DevTools 按钮

### ISSUE THREAD

**Issue by zhuweiyou** [JaveleyQAQ/WeChatOpenDevTools-Python#41]
## 问题描述

3.9.10.19 9115 提示HOOK到, 但没有出现 DevTools 按钮, 所有小程序和网页都没有, 重启微信试了也不行

```
←[0m
←[92m[+] WeChatAppEx.exe 注入成功! ←[0m
←[92m[+] 当前小程序版本: 9115 ←[0m
←[92m[+] 等待小程序加载... ←[0m
←[92m[+] HOOK到小程序加载! wx9627eb7f4b1c69d5 ←[0m
```

![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/8413791/1adcf146-1150-4748-bf08-a4e370d26ab4)

## 环境信息
- **操作系统及版本**：Windows 10
- **编程语言和版本**：Python 3.10.5

**Comment by JaveleyQAQ** [comment]
win11吗

**Comment by zhuweiyou** [comment]
我不是写了 win10

**Comment by zhuweiyou** [comment]
![1714103389685](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/8413791/25b36c26-1c10-48ff-a461-c41aa2bc3553)
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/8413791/c83ee5af-a632-4cf5-8c5f-c1729dd6efce)

**Comment by JaveleyQAQ** [comment]
-。- 属实玄学
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/132129852/8b53f57c-c993-4ad8-ac5a-83057cccc978)

**Comment by zhuweiyou** [comment]
没有 以还原完整F12 这个消息

**Comment by lovexz0519** [comment]
我的也是这种情况

**Comment by lovexz0519** [comment]
是这个报错
[
![1714105287893](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/60094102/f8d1d69b-c88a-41f4-aecb-51202f540401)
](url)

**Comment by lovexz0519** [comment]
关闭微信 重新
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/60094102/43805cf6-7de4-4fe4-a447-1af6cd3b0207)

**Comment by JaveleyQAQ** [comment]
你 -x可以正常使用吗

**Comment by lovexz0519** [comment]
可以正常使用





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Javeley ***@***.***&gt;
发送时间: 2024年4月26日 12:48
收件人: JaveleyQAQ/WeChatOpenDevTools-Python ***@***.***&gt;
抄送: lovexz0519 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JaveleyQAQ/WeChatOpenDevTools-Python] 3.9.10.19 9115 提示成功, 但没有出现 DevTools 按钮 (Issue #41)

**Comment by JaveleyQAQ** [comment]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/132129852/9e6c17f1-ac6b-495f-b482-266c7dcd137e)
 我都是正常使用的。。。 -all 本质上就是先启动了-c 然后在启动-x  你的-c 最后提示了 Frida unable to spawn executable 说明没有办法附加到进程，应该是启动权限的问题，去查查权限相关的资料

**Comment by lovexz0519** [comment]
解决不了啊哥 相关的权限材料

**Comment by lovexz0519** [comment]
方便加微信嘛 ┭┮﹏┭┮

**Comment by leeseett** [comment]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/28776735/130781cd-b55a-4888-86e4-c588413e3852)
只有 vConsole 没有 devtool

**Comment by JaveleyQAQ** [comment]
> ![image](https://private-user-images.githubusercontent.com/28776735/325949182-130781cd-b55a-4888-86e4-c588413e3852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzIyNzIsIm5iZiI6MTcxNDI3MTk3MiwicGF0aCI6Ii8yODc3NjczNS8zMjU5NDkxODItMTMwNzgxY2QtYjU1YS00ODg4LTg2ZTQtYzU4ODQxM2UzODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAyMzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjllM2RlOTJiNWM0ZjM4Yzk2NzVmNmI1MmVjODk2OTljYTRmNTJjZWFjM2I2ZmYxNDVmYWJkOGY4NDU0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AVA4g7awTYEHgXLIwf3pNMDeNeAViJ5_anUz2t9lIt8) 只有 vConsole 没有 devtool

新增了 再试试

**Comment by zhuweiyou** [comment]
> > ![image](https://private-user-images.githubusercontent.com/28776735/325949182-130781cd-b55a-4888-86e4-c588413e3852.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyNzIyNzIsIm5iZiI6MTcxNDI3MTk3MiwicGF0aCI6Ii8yODc3NjczNS8zMjU5NDkxODItMTMwNzgxY2QtYjU1YS00ODg4LTg2ZTQtYzU4ODQxM2UzODUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDAyMzkzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExZjllM2RlOTJiNWM0ZjM4Yzk2NzVmNmI1MmVjODk2OTljYTRmNTJjZWFjM2I2ZmYxNDVmYWJkOGY4NDU0NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AVA4g7awTYEHgXLIwf3pNMDeNeAViJ5_anUz2t9lIt8) 只有 vConsole 没有 devtool
> 
> 新增了 再试试

可以了

**Comment by lovexz0519** [comment]
解决了 感谢🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhuweiyou ***@***.***&gt;
发送时间: 2024年4月28日 10:59
收件人: JaveleyQAQ/WeChatOpenDevTools-Python ***@***.***&gt;
抄送: lovexz0519 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [JaveleyQAQ/WeChatOpenDevTools-Python] 3.9.10.19 9115 提示成功, 但没有出现 DevTools 按钮 (Issue #41)





   
 只有 vConsole 没有 devtool
  
新增了 再试试
  
可以了
