### ISSUE TITLE
大佬能不能加个vx看看，我刷了小程序版本到9115，但是还是没有解决“未找到匹配版本的微信进程或微信未运行”的问题

### ISSUE THREAD

**Issue by iBesokuse** [JaveleyQAQ/WeChatOpenDevTools-Python#42]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/76981514/554e7296-cbfa-4363-bec6-d6baea4c3983)

**Comment by JaveleyQAQ** [comment]
https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/issues/38
