### ISSUE TITLE
请求添加微信小游戏的注入功能

### ISSUE THREAD

**Issue by G-haoyu** [JaveleyQAQ/WeChatOpenDevTools-Python#44]
目前支持的是微信小程序的注入，希望作者增加一下微信小游戏端的注入

- 进程名：WeChatPlayer
- 小游戏版本：4071
- 微信版本：3.9.10.19

**Comment by JaveleyQAQ** [comment]
> 目前支持的是微信小程序的注入，希望作者增加一下微信小游戏端的注入
> 
> * 进程名：WeChatPlayer
> * 小游戏版本：4071
> * 微信版本：3.9.10.19

目前小游戏不也是可以开启consle吗
