### ISSUE TITLE
MACOS缺少配置文件

### ISSUE THREAD

**Issue by marvelliu** [JaveleyQAQ/WeChatOpenDevTools-Python#45]
` % ps aux | grep 'WeChatAppEx' |  grep -v 'grep' | grep  "wmpf-mojo-handle"

marvel           43403   8.1  0.5 444937760  45584   ??  S     2:59PM   0:01.94 /Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx --log-level=2 --lang=en --wechat-files-path=/Users/marvel/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet --no-codecache --product-id=1000 --wechat-sub-user-agent=MicroMessenger/6.8.0(0x16080000) MacWechat/3.8.7(0x13080710) --appshim-flags=7 --client_version=319293200 --bundle-id=5A4RE8SF68.com.tencent.xinWeChat --wmpf-mojo-handle=2992147555`

发现没有相关的版本号，所以分析版本的时候失败。

`marvel@wenmaos-MacBook-Pro WeChatOpenDevTools-Python % python main.py -x
\ \        /\ \  /    __ \           __ __|           |
 \ \  \   /  \  /     |   |  _ \\ \   / |  _ \   _ \  |  __|
  \ \  \ /      \     |   |  __/ \ \ /  | (   | (   | |\__ \
   \_/\_/    _/\_\   ____/ \___|  \_/  _|\___/ \___/ _|____/

        公众号: 一位不愿透露姓名的热心网友
        Github：https://github.com/JaveleyQAQ

> /Users/marvel/Nutstore Files/programs/WeChatOpenDevTools-Python/utils/wechatutils.py(59)extract_version_number()
-> version_match = re.search(r'"version":(\d+)', str)
(Pdb) p str
'/Applications/WeChat.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx --log-level=2 --lang=en --wechat-files-path=/Users/marvel/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet --no-codecache --product-id=1000 --wechat-sub-user-agent=MicroMessenger/6.8.0(0x16080000) MacWechat/3.8.7(0x13080710) --appshim-flags=7 --client_version=319293200 --bundle-id=5A4RE8SF68.com.tencent.xinWeChat --wmpf-mojo-handle=2992147555'
(Pdb) c
[-] 未找到匹配版本的微信进程或微信未运行
marvel@wenmaos-MacBook-Pro WeChatOpenDevTools-Python %`

p.s. 代码中win的路径是\\，但mac下应该是/。

**Comment by marvelliu** [comment]
微信mac版是最新版本，符合readme中的要求

**Comment by JaveleyQAQ** [comment]
mac只有二进制文件 https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/releases/
