### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by White-hua** [JaveleyQAQ/WeChatOpenDevTools-Python#5]
<img width="1107" alt="image" src="https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/100954709/e9e34596-039f-4189-8183-23cb72ebd309">

您好请问这个是啥情况0.0

**Comment by JaveleyQAQ** [comment]
是不是开了两个了，或者用管理员运行试试

**Comment by White-hua** [comment]
emmm只打开了一个微信小程序  然后用以管理员身份开的cmd运行也是这样

**Comment by JaveleyQAQ** [comment]
看着报错就是没有权限注入小程序进程，你试试编译的版本的exe用管理员跑看看

**Comment by 2478641181** [comment]
请问在哪里下载旧版小程序 8555不行 @JaveleyQAQ

**Comment by White-hua** [comment]
emmm我试了用编译后的exe右键管理员运行还是不行

**Comment by JaveleyQAQ** [comment]
看报错就是权限问题，杀毒什么的都关一关，别用exe用main.py呢？

> emmm我试了用编译后的exe右键管理员运行还是不行
