### ISSUE TITLE
搜索会卡住，搜不出数据

### ISSUE THREAD

**Issue by xtxt666** [JaveleyQAQ/WeChatOpenDevTools-Python#51]
win11
py3.8.10
小程序版本8555
![Uploading 17147495552619026373511739124365.jpg…]()

**Comment by JaveleyQAQ** [comment]
已知问题，这个版本搜不出

**Comment by xtxt666** [comment]
应该用哪个版本呢

**Comment by JaveleyQAQ** [comment]
> 应该用哪个版本呢

9xxx

**Comment by xtxt666** [comment]
我安装了最新版，小程序版本依旧是8555，删了很多次文件夹还是一样的结果
