### ISSUE TITLE
# 问题标题：无法开启f12 小程序闪退一次可以打开 所有的小程序如此

### ISSUE THREAD

**Issue by fuckgithubh** [JaveleyQAQ/WeChatOpenDevTools-Python#54]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31642056/9de81025-0195-46fe-92d9-76874092a4a4)
卡在这里 重启微信小程序都不行

**Comment by JaveleyQAQ** [comment]
试试源码允许，打包的exe不是最新的版本

**Comment by fuckgithubh** [comment]
源码运行

**Comment by JaveleyQAQ** [comment]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/132129852/9b6b976d-d1e6-4088-a7a5-6e550cf3b2ae)
麻烦把对应小程序的WeChatAppEx.exe文件单独打包发我一份

**Comment by fuckgithubh** [comment]
1

**Comment by fuckgithubh** [comment]
太大了发不上来

**Comment by fuckgithubh** [comment]
我加您一个其他联系方式可以么 或者我的q 1321307081

**Comment by fuckgithubh** [comment]
@JaveleyQAQ

**Comment by fuckgithubh** [comment]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31642056/f0888131-f02c-4f77-b196-1babdf1448ee)

**Comment by fuckgithubh** [comment]
链接：https://pan.baidu.com/s/19UrG4jFBZPEZxhmDzaPTtg?pwd=8f00 
提取码：8f00
