### ISSUE TITLE
加载成功了 为什么没有devtools

### ISSUE THREAD

**Issue by pztpzsapp** [JaveleyQAQ/WeChatOpenDevTools-Python#6]
# 上个星期都有，今天突然就没了
![图片](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/152942313/da7f3976-3e4a-491b-93b8-f5b8aafaa9b5)

# 如图
![图片](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/152942313/21acec0b-2173-4c95-977d-a40c76f96619)

**Comment by JaveleyQAQ** [comment]
对应版本地址文件可能更新了，尝试删除一下小程序版本的目录，让微信重新生成换成别的版本试试，8555我今天测试还是可以用的

**Comment by pztpzsapp** [comment]
> 对应版本地址文件可能更新了，尝试删除一下小程序版本的目录，让微信重新生成换成别的版本试试，8555我今天测试还是可以用的

怎么查看 小程序版本的目录 方便告知在哪里吗 （不太懂

**Comment by pztpzsapp** [comment]
你好 重启电脑 解决问题了！
