### ISSUE TITLE
小程序闪退9129最新版本

### ISSUE THREAD

**Issue by 1006400320** [JaveleyQAQ/WeChatOpenDevTools-Python#62]
测试环境：window11，微信版本3.9.10.19，小程序版本9129
测试小程序：谷千文化/wx92cf5007067d7393
现象：
1. 运行main.py后，
2. 打开小程序，显示[+] HOOK到小程序加载! wx92cf5007067d7393
3. 强制退出，小程序直接闪退

**Comment by JaveleyQAQ** [comment]
单这个小程序还是都是？

**Comment by 1006400320** [comment]
所有小程序都会闪退哦
