### ISSUE TITLE
# 执行python main.py -c 报错：TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by LBZHK** [JaveleyQAQ/WeChatOpenDevTools-Python#68]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/57286658/a7dab7af-41f2-4e34-9a45-34dc7ae0f159)

**Comment by AkaRamen** [comment]
在wechatutils.py 顶部直接import winreg解决。

**Comment by Latucc** [comment]
你的错误是因为没有定位到微信安装路径，你应该用的是破解绿色版微信，需要在在commons.py的62行，手动设置wechatEXEpath

**Comment by selfstduy** [comment]
找不到这个commons文件怎么办 ，里面报错的地方在本地根本找不到

**Comment by 2700zc** [comment]
如果你使用了RevokeMsgPatcher防撤回插件，请先还原后再重试就行了，亲测

**Comment by selfstduy** [comment]
喔喔 谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年7月5日(星期五) 上午8:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [JaveleyQAQ/WeChatOpenDevTools-Python] # 执行python main.py -c 报错：TypeError: &#39;NoneType&#39; object is not subscriptable (Issue #68)














 
如果你使用了RevokeMsgPatcher防撤回插件，请先还原后再重试就行了，亲测

**Comment by JaveleyQAQ** [comment]
解决了
