### ISSUE TITLE
8555不行

### ISSUE THREAD

**Issue by lake2** [JaveleyQAQ/WeChatOpenDevTools-Python#7]
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/6293752/1bb42c84-0917-4558-a412-60a06c73a947)

**Comment by rayepeng** [comment]
同测试不行

**Comment by Amzza0x00** [comment]
我替换了dll，也是8555为啥内置浏览器没有f12

**Comment by rayepeng** [comment]
> 我替换了dll，也是8555为啥内置浏览器没有f12

你成功了吗，求问

**Comment by pztpzsapp** [comment]
替换这个 hook.js跟8555.json 就可以了。。。  url：https://github.com/x0tools/WeChatOpenDevTools  微信版本：3.9.9.43

**Comment by JaveleyQAQ** [comment]
过年一直没看-。- 更新了
