### ISSUE TITLE
最新版本（3.8.8.18）微信mac（intel）系统下报错

### ISSUE THREAD

**Issue by kmustriver** [JaveleyQAQ/WeChatOpenDevTools-Python#71]
mac intel 环境
微信版本:3.8.8.18
报错信息：
	Error: can't decode byte 0x89 in position 2
    at <anonymous> (frida/runtime/core.js:145)
    at readStdString (/script1.js:24)
    at onEnter (/script1.js:106)
报错小程序：所有
<img width="404" alt="image" src="https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/10754141/a354f8bd-6848-4425-919e-508e3f6e9071">

**Comment by JaveleyQAQ** [comment]
用源码，编译的并不是最新的
