### ISSUE TITLE
大佬们注入有问题frida.NotSupportedError: unable to spawn executable at 'D:\wechat\WeChat.exe': 0x00000032

### ISSUE THREAD

**Issue by hatjwe** [JaveleyQAQ/WeChatOpenDevTools-Python#72]
大佬们，我在执行python -c时报错这个，是无法注入吗
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/42887236/244daef9-c9b4-4ae8-bd2f-76066ef4cc02)

**Comment by YCC-324** [comment]
您好，我也遇到了这个问题，请问您是怎么解决的呢，谢谢
