### ISSUE TITLE
# 无法hook并发现刚打开小程序得参数生成过程

### ISSUE THREAD

**Issue by 7BlackJack** [JaveleyQAQ/WeChatOpenDevTools-Python#73]
有的参数是小程序刚打开得那个瞬间服务器响应或者JS生成的，但是WXDevTools 目前无法实现监听抓取这一过程数据包，希望这一过程能够实现或者完善，感谢作者

**Comment by JaveleyQAQ** [comment]
找个js从最开始下断点，别关掉窗口，重新再打开一个调试面板
