### ISSUE TITLE
3.9.11.17用不了这个工具了

### ISSUE THREAD

**Issue by NothingButStupid** [JaveleyQAQ/WeChatOpenDevTools-Python#75]
请问作者3.9.11.17 用不了这个工具了，电脑下载老版本的微信也会被新版本微信覆盖 怎么办呢 求教感谢您

**Comment by mingzitainanle** [comment]
![image](https://github.com/user-attachments/assets/9a8385fd-a65b-457c-8e1e-652428da0a6f)
3.9.11.25 也不行了
