### ISSUE TITLE
没有这个压缩包WeChatWin3.9.8.25_x64.zip

### ISSUE THREAD

**Issue by admin1test** [JaveleyQAQ/WeChatOpenDevTools-Python#8]
请问下[WeChatWin3.9.8.25_x64.zip](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/releases/download/0.1/WeChatWin3.9.8.25_x64.zip) 这个压缩包还有么？

**Comment by JaveleyQAQ** [comment]
https://www.lanzv.com/idukB1osluaf 这个是老版本的方法了，我不确定在新版本能不能用，自己还没尝试，过段时间再发新的hook内置浏览器脚本
