### ISSUE TITLE
win的编译版开启不了内嵌浏览器的devtools

### ISSUE THREAD

**Issue by foxhui** [JaveleyQAQ/WeChatOpenDevTools-Python#81]
尝试给exe创建快捷方式后加上-c会报错
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31238038/7a89062d-de55-4abf-9b81-dd2282b2f92c)
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31238038/14a926d9-5e98-43fc-a2ac-fdace48d2a91)

这个版本的编译版：[0.3.1](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/releases/tag/0.3.1)
微信版本：
![image](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/31238038/9075d112-d402-40de-a2a9-95daac860164)

**Comment by JaveleyQAQ** [comment]
exe不是最新的 命令冲突了 换源码
