### ISSUE TITLE
大众点评小程序美食接口无法返回数据

### ISSUE THREAD

**Issue by wpl427** [JaveleyQAQ/WeChatOpenDevTools-Python#85]
![微信图片编辑_20240710172338](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/assets/47511360/531f2727-eae5-4360-b9cb-90f2af6ff97c)

**Comment by zyq9233** [comment]
兄弟解决了么

**Comment by zyq9233** [comment]
这个不是工具的问题，是小程序自己有环境检测。参考我已关闭的 issue

**Comment by JaveleyQAQ** [comment]
https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/issues/90
