### ISSUE TITLE
# 在翻阅文档和视频后 遇到 mac系统 装的虚拟机 虚拟机装的windows10 微信版本是3.9.11.19 执行 python main.py -x  提示 未找到匹配版本的微信进程或微信未运行

### ISSUE THREAD

**Issue by fujiangren** [JaveleyQAQ/WeChatOpenDevTools-Python#87]
# 🙋提问智力得分表

|我在遇到了一个问题，在翻阅文档和视频后，这里是报错截图，我参考了百度或谷歌中xxx文章进行解决，但仍不能解决! 

![1234](https://github.com/user-attachments/assets/66a0f1a5-ae7f-4992-b8b1-749059c97c52)
![1234](https://github.com/user-attachments/assets/f0c82b28-42fc-45c9-9b52-e4f8c5fda858)

## 问题描述
- 请在这里提供问题的详细描述，包括您遇到的具体问题和任何相关的背景信息。

## 环境信息
- **操作系统及版本**：macOS Bigsur 11.7.10 vmWare虚拟机 虚拟机装 Windows 10, win10 装微信3.9.11.19
- python 3.11.9 下载是 https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python 解压后 切换到 WeChatOpenDevTools-Python-main目录 执行 pip3  install -r requirements.txt  然后执行 python main.py -x  
- 结果提示 未找到匹配版本的微信进程或微信未运行 前提是微信已经装好 小程序已经打开 我阅读了 没有找到解决方案 特请假 万分感谢
-

**Comment by k1ngbanana** [comment]
这个版本不在支持范围里面，安装一下旧版试试
