### ISSUE TITLE
# 某点评页面加载不出来

### ISSUE THREAD

**Issue by zyq9233** [JaveleyQAQ/WeChatOpenDevTools-Python#90]
## 环境信息
- **操作系统及版本**：Windows 10
- **编程语言和版本**：例如 Python 3.9.0
- **wx版本**：3.9.10.19
- **小程序版本**：8555
- **devTools 版本**： [WeChatOpenDevTools](https://github.com/JaveleyQAQ/WeChatOpenDevTools-Python/releases/tag/0.3.1)

## 问题描述
1. 使用某车之家，测试开发者工具，network， 有数据流，表示安装正常。
2. 使用某众点评，不注入 WeChatOpenDevTools， 页面正常加载。
3. 使用某众点评，注入 WeChatOpenDevTools， 可以打开开发者工具，但是数据流加载不出来

## 预期结果
-  数据流正常

**Comment by kerr1024** [comment]
老哥解决了吗

**Comment by zyq9233** [comment]
> 老哥解决了吗

后端返回403解决了，某评有环境检测。找到环境检测的地方，把正确的环境代码重新复制就行了。后端可以正常返回接口数据。

**Comment by zyq9233** [comment]
不是工具的bug，是网站有环境检测。

**Comment by chenjunjie1031** [comment]
> > 老哥们
> 
> 返回403解决了，某评有环境检测。找到环境检测的地方，把正确的环境代码重新复制就行了。实验室可以正常返回接口数据。

请问如何找到检测位置呢

**Comment by kerr1024** [comment]
> > 老哥解决了吗
> 
> 后端返回403解决了，某评有环境检测。找到环境检测的地方，把正确的环境代码重新复制就行了。后端可以正常返回接口数据。

请教老哥修改什么环境参数，可以让请求通过呢，我看到了enable_debug, 改了也没用

**Comment by kerr1024** [comment]
> > 老哥解决了吗
> 
> 后端返回403解决了，某评有环境检测。找到环境检测的地方，把正确的环境代码重新复制就行了。后端可以正常返回接口数据。

请问环境监测的什么参数呢，一直没找到原因 @zyq9233
