### ISSUE TITLE
Mac M1运行报错 

### ISSUE THREAD

**Issue by shixiaoxianga** [JaveleyQAQ/WeChatOpenDevTools-Python#98]
**sudo open WeChatOpenDevTools-macos-x64**

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/4bc17284-9c9f-44b2-9845-abf229b91f80">

设备类型：MacBookPro18,3
系统版本：版本14.5（版号23F79）
系统语言：zh-Hans
微信版本：[2024-06-07 18:07:01] v3.8.8.18 (28486) #fcae08238d 
微信语言：zh-Hans
历史版本：[2024-07-24 10:00:01] v3.7.0.17 (25067) #0528ee5334
网络状态：Reachable via WiFi or Ethernet
显  示  器：*(1800x1169)/Retina

<img width="715" alt="image" src="https://github.com/user-attachments/assets/6e7fc814-916f-4cb5-8ab0-7f3a5e2c814d">

[+] WeChatAppEx 进程PID: 59531
Error: Unable to access process with pid 59531 from the current user account

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

<img width="1330" alt="image" src="https://github.com/user-attachments/assets/a68f264f-04f4-4a0c-8836-a8cf52b82fef">

wei    59531   0.0  0.3 444878496  47248   ??  S     2:21PM   0:01.96 /Applications/微信 2.app/Contents/MacOS/WeChatAppEx.app/Contents/MacOS/WeChatAppEx-log-level=2 --lang=zh-CN --wechat-files-path=/Users/xiangzhongwei/Library/Containers/com.tencent.xinWeChat/Data/.wxapplet --no-codecache --product-id=1000 --wechat-sub-user-agent=MicroMessenger/6.8.0(0x16080000) MacWechat/3.8.8(0x13080812) --appshim-flags=7 --client_version=319293458 --bundle-id=5A4RE8SF68.com.tencent.xinWeChat --wmpf-mojo-handle=1361925839

**Comment by shixiaoxianga** [comment]
可以支持下ARM架构吗

**Comment by JaveleyQAQ** [comment]
很快
